### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by nfrankel** [nfrankel/hazelcast-kotlindsl#5]
https://github.com/nfrankel/hazelcast-kotlindsl/actions/runs/73504316

**Comment by amrsamii** [comment]
The problem is SONAR_TOKEN is added as a secret in settings in my Repo but it is not added your Repo, so SonarCloud analysis could not be triggered and so GitHub actions returns with error. here it is, it is successful in my Repo: https://github.com/amrsamii/hazelcast-kotlindsl/actions/runs/73577532

**Comment by amrsamii** [comment]
The problem is, SonarCloud says that you are not authorized to run analysis, so SonarCloud analysis could not be triggered and so GitHub actions returns with error. here it is, it is successful in my Repo: https://github.com/amrsamii/hazelcast-kotlindsl/actions/runs/73577532

**Comment by amrsamii** [comment]
solutions could be
 - make anyone executes analysis
 - add you to the organization in SonarCloud

**Comment by nfrankel** [comment]
I've added a `SONAR_TOKEN` secret, so please add me to your org in SonarCloud

**Comment by amrsamii** [comment]
it is done, I also gave you permission to execute analysis.
